packages:
  - 'packages/*'
  - 'site'
overrides:
  '@jsforce/jsforce-node': ^3.10.25
onlyBuiltDependencies:
  - nx
minimumReleaseAgeExclude:
  - '@simplysf/simply-core@1.1.1 || 1.5.1'
  - eslint@10.9.0
allowBuilds:
  esbuild: true
  nx: true
  unrs-resolver: true
